security:
    role_hierarchy:
        ROLE_USUARIO:    IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:       ROLE_USUARIO
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY ,ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN_INS: [ROLE_ADMIN, IS_AUTHENTICATED_ANONYMOUSLY ,ROLE_ALLOWED_TO_SWITCH]
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext        
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm:  sha1
            iterations: 1
            encode_as_base64: false
            

    providers:
        default_provider:
            memory:
                users:
                    raspinu: { password:0cab848c82426d8cd47736c8fb42f1403047a661, roles: 'ROLE_SUPER_ADMIN'} 
                    Edu: { password:0cab848c82426d8cd47736c8fb42f1403047a661, roles: 'ROLE_SUPER_ADMIN_INS'} 

    firewalls:
        secured_area:
            pattern:    /*
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path: /logout
                target: /login

    access_control:
      - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: /, roles: [ROLE_USUARIO,ROLE_VISITA] }

