ofi_gestion_homepage:
    pattern:  /
    defaults: { _controller: OfiGestionBundle:Fijas:index }

ofi_gestion_crearempresa:
    pattern:  /crear-empresa
    defaults: { _controller: OfiGestionBundle:Empresa:crear }

ofi_gestion_nuevoempresa:
    pattern:  /nuevo-empresa
    defaults: { _controller: OfiGestionBundle:Empresa:nuevo }

ofi_gestion_editarempresa:
    pattern:  /editar-empresa/{id}
    defaults: { _controller: OfiGestionBundle:Empresa:editar }


ofi_gestion_actualizarempresa:
    pattern:  /actualizar-empresa/{id}
    defaults: { _controller: OfiGestionBundle:Empresa:actualizar }

ofi_gestion_listarempresa:
    pattern:  /listado-empresas/{filtro}
    defaults: { _controller: OfiGestionBundle:Empresa:listar }


ofi_gestion_eliminarempresa:
    pattern:  /listado-empresas/{id}/{ok}
    defaults: { _controller: OfiGestionBundle:Empresa:eliminar }



ofi_gestion_crearccorreo:
    pattern:  /crear-correo/{id}
    defaults: { _controller: OfiGestionBundle:Correo:crear }

ofi_gestion_eliminarcorreo:
    pattern:  /eliminar-correo/{id}
    defaults: { _controller: OfiGestionBundle:Correo:eliminar }


ofi_gestion_crearctelefono:
    pattern:  /crear-telefono/{id}
    defaults: { _controller: OfiGestionBundle:Telefono:crear }

ofi_gestion_eliminartelefono:
    pattern:  /eliminar-telefono/{id}
    defaults: { _controller: OfiGestionBundle:Telefono:eliminar }

ofi_gestion_crearcdatofac:
    pattern:  /crear-datofac/{id}
    defaults: { _controller: OfiGestionBundle:DatoFac:crear }


ofi_gestion_crearcdatofacAdmin:
    pattern:  /crear-datofacAdmin/{id}
    defaults: { _controller: OfiGestionBundle:DatoFac:crearAdmin }

ofi_gestion_eliminardatofac:
    pattern:  /eliminar-datofac/{id}
    defaults: { _controller: OfiGestionBundle:DatoFac:eliminar }

ofi_gestion_eliminardatofacAdmin:
    pattern:  /eliminar-datofacAdmin/{id}
    defaults: { _controller: OfiGestionBundle:DatoFac:eliminarAdmin }


ofi_gestion_crearfactura:
    pattern:  /crear-factura
    defaults: { _controller: OfiGestionBundle:Factura:crear }

ofi_gestion_listarfactura:
    pattern:  /listar-factura
    defaults: { _controller: OfiGestionBundle:Factura:listar }
    
    
ofi_gestion_nuevafactura:
    pattern:  /nueva-factura
    defaults: { _controller: OfiGestionBundle:Factura:nuevo }    

ofi_gestion_editarfactura:
    pattern:  /editar-factura/{id}
    defaults: { _controller: OfiGestionBundle:Factura:editar }

ofi_gestion_actualizafactura:
    pattern:  /actualiza-factura/{id}
    defaults: { _controller: OfiGestionBundle:Factura:actualizar }


ofi_gestion_editarAdminConfig:
    pattern:  /editar-configuracion/{id}
    defaults: { _controller: OfiGestionBundle:AdminConfig:editar }

ofi_gestion_updateAdminConfig:
    pattern:  /actualizar-config/{id}
    defaults: { _controller: OfiGestionBundle:AdminConfig:update }
