ofi_gestion_homepage:
    pattern:  /
    defaults: { _controller: OfiGestionBundle:Fijas:index }

ofi_gestion_crearcliente:
    pattern:  /crear-cliente
    defaults: { _controller: OfiGestionBundle:Cliente:crear }

ofi_gestion_editarcliente:
    pattern:  /editar-cliente/{id}
    defaults: { _controller: OfiGestionBundle:Cliente:editar }


ofi_gestion_actualizarcliente:
    pattern:  /actualizar-cliente/{id}
    defaults: { _controller: OfiGestionBundle:Cliente:actualizar }

ofi_gestion_listarcliente:
    pattern:  /listado-clientes/
    defaults: { _controller: OfiGestionBundle:Cliente:listar }


ofi_gestion_eliminarcliente:
    pattern:  /listado-clientes/{id}/{ok}
    defaults: { _controller: OfiGestionBundle:Cliente:eliminar }



ofi_gestion_crearccorreo:
    pattern:  /crear-correo/{id}
    defaults: { _controller: OfiGestionBundle:Correo:crear }

ofi_gestion_eliminarcorreo:
    pattern:  /eliminar-correo/{id}
    defaults: { _controller: OfiGestionBundle:Correo:eliminar }


ofi_gestion_crearctelefono:
    pattern:  /crear-telefono/{id}
    defaults: { _controller: OfiGestionBundle:Telefono:crear }

ofi_gestion_eliminartelefono:
    pattern:  /eliminar-telefono/{id}
    defaults: { _controller: OfiGestionBundle:Telefono:eliminar }

ofi_gestion_crearcdatofac:
    pattern:  /crear-datofac/{id}
    defaults: { _controller: OfiGestionBundle:DatoFac:crear }

ofi_gestion_eliminardatofac:
    pattern:  /eliminar-datofac/{id}
    defaults: { _controller: OfiGestionBundle:DatoFac:eliminar }
