parameters:
#    ofi_gestion.example.class: Ofi\GestionBundle\Example

services:
#    ofi_gestion.example:
#        class: %ofi_gestion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
