<?php

namespace Ofi\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatosFacturacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosFacturacionRepository extends EntityRepository
{
	
	public function contarDatosFac($id)
	{
	return $this->getEntityManager()
            ->createQuery('SELECT count(s.id) AS total FROM 
						  OfiGestionBundle:DatosFacturacion s
						  WHERE s.empresa = :idempresa ')
            ->setParameter('idempresa',$id)
            ->getResult();
		
	}
	
	
}
