<?php

namespace Ofi\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleRepository extends EntityRepository
{
	public function ListadoDisponibles($idproyecto)
	{
		return $this->getEntityManager()
				->createQuery('SELECT d FROM 
							  OfiGestionBundle:Detalle d
							  WHERE 
							  d.proyecto = :idproyecto
							  AND d.factura IS NULL')
				->setParameter('idproyecto',$idproyecto)
				->getResult();
		
	}

	public function ListadoInsertadosenFac($idproyecto,$idfactura)
	{
		return $this->getEntityManager()
				->createQuery('SELECT d FROM 
							  OfiGestionBundle:Detalle d
							  WHERE 
							  d.proyecto = :idproyecto
							  AND d.factura=:idfactura')
				->setParameter('idproyecto',$idproyecto)
				->setParameter('idfactura',$idfactura)
				->getResult();
		
	}
	
}
