<?php

namespace Ofi\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
	
	public function ListaEmpresasFiltro($filtro)
	{
	return $this->getEntityManager()
            ->createQuery('SELECT e FROM 
						  OfiGestionBundle:Empresa e
						  WHERE e.tipo = :filtro ')
            ->setParameter('filtro',$filtro)
            ->getResult();
		
	}
	
	
}
