<?php

namespace Ofi\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IrpfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IrpfRepository extends EntityRepository
{
	
	public function BuscaIrpfs($fecha)
	{
		 return $this->getEntityManager()
				->createQuery('SELECT i FROM 
							  OfiGestionBundle:Irpf i
							  WHERE 
							  :lafecha between i.inicio and i.final')
				->setParameter('lafecha',$fecha)
				->getResult();
		
		
		
	}
	
	
}
