<?php

namespace Ofi\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IvaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IvaRepository extends EntityRepository
{
	
	public function BuscaIvas($fecha)
	{
		 return $this->getEntityManager()
				->createQuery('SELECT i FROM 
							  OfiGestionBundle:Iva i
							  WHERE 
							  :lafecha between i.inicio and i.final')
				->setParameter('lafecha',$fecha)
				->getResult();
		
		
		
	}

	
	
}
