<?php

namespace Ofi\GestionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoRepository extends EntityRepository
{
	
	public function ListaProyectosEmpresa($idempresa)
	{
	return $this->getEntityManager()
            ->createQuery('SELECT p FROM 
						  OfiGestionBundle:Proyecto p
						  WHERE p.empresa = :idempresa 
						  ORDER BY p.fechainicio DESC')
            ->setParameter('idempresa',$idempresa)
            ->getResult();
		
	}
	
}
